version: "3.7"
services:
  src:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    volumes:
      - "./src/:/var/www/html/"
    ports:
      - "80:80"
  db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_DATABASE: "launcher"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "root-password"
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: on-failure
    environment:
      PMA_HOST: db
      PMA_USER: "root"
      PMA_PASSWORD: "password"
    ports:
      - "3306:80"
    expose:
      - "3306"
volumes:
  db-data:
